-- This file has been generated by Ion. Do not edit.
return {
    ["jicknan"] = {
    },
    ["wheather"] = {
    },
    ["uptime"] = {
    },
    ["date"] = {
        ["date_format"] = "%a %Y-%m-%d %H:%M",
    },
    ["sysmon"] = {
    },
    ["load"] = {
    },
    ["mail"] = {
    },
}

