#!/bin/sh

time=`date --iso-8601`
to=li.hui.fang@sze.epson.com.hk
cc=jick.nan@gmail.com
subject="[$time]Japanese news"

mail_dir=$HOME/.mutt/leebox
http_dir=http://127.0.0.1/rss/scripts
web_dir=$HOME/web/rss/scripts

log_file=$mail_dir/wget.log
out_file=$web_dir/lee.html
#wget_file=$http_dir/lee.php
wget_file=http://www.china.co.jp/xiandialy/dialy-No2_2.htm

lynx_file=$http_dir/lee.html
mail_file=$mail_dir/mail_$time

if [ -f $out_file ] 
then 
  mv $out_file $out_file.p 
fi 

wget -o $log_file -O $out_file $wget_file

#lynx -display_charset=utf-8 -dump $lynx_file > $mail_file

cat >> $mail_file << EOF

EOF

mutt -a $out_file -s $subject -c $cc  $to < $mail_file
