#!/bin/sh
# n4s.sh - Need for Speed, simple testing the speed of kernel
#	   Form: http://kerneltrap.org/node/6363
# Created at Tue 20 Jun 2006 01:36:24 PM CST by jick.
# 

# Put here amount of ram you have in megabytes
RAM="1024"
FILE1=$(mktemp)
FILE2=$(mktemp)
time dd if=/dev/zero of=$FILE1 count=$[2*$RAM] bs=$[1024*1024]
time sync
time cp $FILE1 $FILE2
time rm $FILE1 $FILE2
