#!/bin/bash

SRC=/data/podcast
M3U=castget-`date --iso-8601`.m3u
DEST=/mnt/s1mp3/`date --iso-8601`

mount /mnt/s1mp3
mkdir -p $DEST

for file in `cat $SRC/$M3U`;
do
    echo $file;
    if [ -f $file ]; then
	cp -av $file $DEST
    fi
done

umount /mnt/s1mp3
