#!/bin/sh

cd /jick/slackware/slackware-current

#lftp ftp.slackware.com/pub/slackware/slackware-current/ -e ' 
lftp slackware.mirrors.tds.net:/pub/slackware/slackware-current/ -e ' 
get BOOTING.TXT && 
get CHECKSUMS.md5 && 
get CHECKSUMS.md5.asc && 
get -c COPYING && 
get COPYRIGHT.TXT && 
get CRYPTO_NOTICE.TXT && 
get CURRENT.WARNING && 
get ChangeLog.txt && 
get FAQ.TXT && 
get FILELIST.TXT && 
get GPG-KEY && 
get PACKAGES.TXT && 
get README.NPTL && 
get SPEAKUP_DOCS.TXT && 
get SPEAK_INSTALL.TXT && 
get Slackware-HOWTO && 
get UPGRADE.TXT && 
mirror -c --parallel=2 --delete --verbose extra && 
mirror -c --parallel=2 --delete --verbose isolinux && 
mirror -c --parallel=2 --delete --verbose kernels && 
mirror -c --parallel=2 --delete --verbose rootdisks && 
mirror -c --parallel=2 --delete --verbose slackware && 
mirror -c --parallel=2 --delete --verbose source && 
mirror -c --parallel=2 --delete --verbose testing && 
quit'
